import * as APIUtil from '../util/RestaurantDetailsApiUtil';

export const RECEIVE_RESTAURANT_DETAILS = 'RECEIVE_RESTAURANT_DETAILS';
export const RECEIVE_RESTAURANT_PHOTO = 'RECEIVE_RESTAURANT_PHOTO';
export const RECEIVE_RESTAURANT_MAP = 'RECEIVE_RESTAURANT_MAP';
